### ISSUE TITLE
Enable/disable peers

### ISSUE THREAD

**Issue by Nikita01471** [donaldzou/WGDashboard#377] opened 2024-09-09 11:58 UTC
Hello!
Have some issues whis enabled peers.

After testing buttons and use "disable peer", can't enable peers back. 
Deleting disabled peers is also unavailable.

**Comment by donaldzou** [comment] 2024-09-09 14:42
Hi! Do you mind posting a screenshot please?

**Comment by Nikita01471** [comment] 2024-09-10 05:08
![IMG_20240909_192821_499](https://github.com/user-attachments/assets/20671827-fda4-48af-8cd5-1cdfd8b2b2aa)

**Comment by NOXCIS** [comment] 2024-09-13 00:58
@donaldzou its a bug in you 4.1 dev branch. Disabling peers with preshared keys breaks the config.

**Comment by DaanSelen** [comment] 2024-11-09 01:08
> @donaldzou its a bug in you 4.1 dev branch. Disabling peers with preshared keys breaks the config.

v4.1 just got launched, is this still a bug? I was not able to reproduce with a preshared key.

**Comment by NOXCIS** [comment] 2024-11-10 03:01
@DaanSelen Was fixed, now broken agiain among other things.

Running Demo below.

http://demo.noxcis.com:10086/
username: admin
password: catinthehat

**Comment by donaldzou** [comment] 2024-11-13 00:46
Could not reproduce with Preshared Key enabled for a peer. Will close this issue for now as it is related to a previous version.

**Comment by NOXCIS** [comment] 2024-11-14 10:02
def addpeer is missing the weird step to copy from file, probably forgot it in refractor.

demo.noxcis.com <-Running with your Digital Ocean Affialte Link
username: admin
password: 6j2KPfPTBUrTEKD

<img width="1306" alt="Screenshot 2024-11-14 at 4 56 58 AM" src="https://github.com/user-attachments/assets/d5081740-f000-4db5-870d-1f46330a07e7">
<img width="1553" alt="Screenshot 2024-11-14 at 4 52 36 AM" src="https://github.com/user-attachments/assets/ea7d7627-7bc4-49de-a39c-0f207241679b">
<img width="1379" alt="Screenshot 2024-11-14 at 4 59 47 AM" src="https://github.com/user-attachments/assets/1e5606b7-3d13-4a17-ae0d-9c556cda1f25">



Docker Compose Used
```yaml
services:
  wireguard-dashboard:
    image: donaldzou/wgdashboard:latest
    restart: unless-stopped
    container_name: wgdashboard
    #environment:
      #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
      #- global_dns=        # <--- Set global DNS address, default: 1.1.1.1.
      #- isolate=           # <--- Set the interfaces that will disallow peer communication, default: 'none'.
      #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
    ports:
      - 80:10086/tcp
      - 51820:51820/udp
    volumes:
      - conf:/etc/wireguard
      - data:/data
    cap_add:
      - NET_ADMIN

volumes:
  conf:
  data:

```

**Comment by donaldzou** [comment] 2024-11-14 10:12
> def addpeer is missing the weird step to copy from file, probably forgot it in refractor.
> 
> demo.noxcis.com <-Running with your Digital Ocean Affialte Link username: admin password: 6j2KPfPTBUrTEKD
> 
> <img alt="Screenshot 2024-11-14 at 4 56 58 AM" width="1306" src="https://private-user-images.githubusercontent.com/26854391/386143238-d5081740-f000-4db5-870d-1f46330a07e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzkyMDIsIm5iZiI6MTczMTU3ODkwMiwicGF0aCI6Ii8yNjg1NDM5MS8zODYxNDMyMzgtZDUwODE3NDAtZjAwMC00ZGI1LTg3MGQtMWY0NjMzMGEwN2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ODlmM2Q0ZDcyYTFmNzJhNTBiODQxZWY0MTNhYmVlZjFjOTY1YTI3YzMwZmM2Zjc5NzIzZjkyMjVmOTI2ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hJzd40tLGO-yuyWkr5Zsw-Vreft6X286UXb9jKKrJOM"> <img alt="Screenshot 2024-11-14 at 4 52 36 AM" width="1553" src="https://private-user-images.githubusercontent.com/26854391/386143330-ea7d7627-7bc4-49de-a39c-0f207241679b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzkyMDIsIm5iZiI6MTczMTU3ODkwMiwicGF0aCI6Ii8yNjg1NDM5MS8zODYxNDMzMzAtZWE3ZDc2MjctN2JjNC00OWRlLWEzOWMtMGYyMDcyNDE2NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDM1OWQwZTM3OWM0MTNjZWI5MjI3MWIyODZkMmRlODVjNDUzM2RlMTNhZTFkOTI0MTg1ZmVkODAzOTg3YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s3iRN26j7yr1DTFY3naVP23ZbaCjGXCQtfdpQmqxWrw"> <img alt="Screenshot 2024-11-14 at 4 59 47 AM" width="1379" src="https://private-user-images.githubusercontent.com/26854391/386144160-1e5606b7-3d13-4a17-ae0d-9c556cda1f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NzkyMDIsIm5iZiI6MTczMTU3ODkwMiwicGF0aCI6Ii8yNjg1NDM5MS8zODYxNDQxNjAtMWU1NjA2YjctM2QxMy00YTE3LWFlMGQtOWM1NTZjZGExZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYWNmMWViMTE2MzkxOGQxODM2MGQ4NWExNjgwMDdjN2Y5MTZjNmI3OTM0MGViYTk0NDQwZmVjNGY4NzllMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RsN9ZeXEkWFInIuGYC55rZjKkkAnYQvhY6SXhk3hQ70">
> Docker Compose Used
> 
> ```yaml
> services:
>   wireguard-dashboard:
>     image: donaldzou/wgdashboard:latest
>     restart: unless-stopped
>     container_name: wgdashboard
>     #environment:
>       #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
>       #- global_dns=        # <--- Set global DNS address, default: 1.1.1.1.
>       #- isolate=           # <--- Set the interfaces that will disallow peer communication, default: 'none'.
>       #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
>     ports:
>       - 80:10086/tcp
>       - 51820:51820/udp
>     volumes:
>       - conf:/etc/wireguard
>       - data:/data
>     cap_add:
>       - NET_ADMIN
> 
> volumes:
>   conf:
>   data:
> ```

Hi @NOXCIS, what do you mean by missing? The feature is for user who just want to copy Peer's configuration instead of downloading or scanning the QR Code

**Comment by NOXCIS** [comment] 2024-11-14 10:45
@donaldzou you fixed it in an old version, i think it got left out in the update. Peers with preshared keys enabled cant connect.

**Comment by donaldzou** [comment] 2024-11-14 12:38
In the latest version it is in there https://github.com/donaldzou/WGDashboard/blob/811ed3251bfb798c293d19f0baaae4b618af46db/src/dashboard.py#L787-L796

Also pulled from latest

https://github.com/user-attachments/assets/397ce0b1-495b-4c44-a444-d81a244919d7

Maybe you are viewing an older version of `dashboard.py`

**Comment by NOXCIS** [comment] 2024-11-14 18:56
Oh i think theres a miscomunication. I spun up that stuff this morning from the main branch. https://github.com/donaldzou/WGDashboard/blob/main/src/dashboard.py#L755-L764. There ya go. Thanks.

**Comment by donaldzou** [comment] 2024-11-15 05:47
> You fixed it in this commit [17a9fe5](https://github.com/donaldzou/WGDashboard/commit/17a9fe50246dab05d214c2742703e3e378d37242)

Ah yes, my bad.. #494 should fix this issue.

**Comment by donaldzou** [comment] 2024-11-15 05:51
> Also add QEMU to your docker-build workflow to ensure proper crosscompilation. I ran into that issue a while back becuase i mostly develope stuff on ARM64 (M2 macbook), before testing across my other devices, while not realizing github doesnt have ARM servers. Dont know if it will occur with your image, but still good practice.

Yes I think a user in Discord mentioned this issue last week and @DaanSelen patched it

https://github.com/donaldzou/WGDashboard/blob/811ed3251bfb798c293d19f0baaae4b618af46db/.github/workflows/docker-build.yaml#L33-L39

**Comment by NOXCIS** [comment] 2024-11-15 07:39
@donaldzou Respectfully, that workflow is still very much incorrect and missing QEMU which is needed for multi platform builds according to the Docker Docs. Especially when cross compiling for arm devices when using an x86 sever.

https://docs.docker.com/build/building/multi-platform/

https://docs.docker.com/build/ci/github-actions/multi-platform/

Don't blame me blame the docs, it was a pain in my a** a month ago.
🙂

**Comment by DaanSelen** [comment] 2024-11-15 10:24
@donaldzou, @NOXCIS is right. I'll look at the docs and the example from WireGate to apply QEMU setup.

**Comment by DaanSelen** [comment] 2024-11-15 10:27
Regarding the issue, can people verify and review the proposed changes in https://github.com/donaldzou/WGDashboard/tree/fix-preshared-key

**Comment by donaldzou** [comment] 2024-11-15 10:58
> @donaldzou, @NOXCIS is right. I'll look at the docs and the example from WireGate to apply QEMU setup.

@DaanSelen thank u thank u!

**Closed** 2024-11-15 11:06 UTC
Labels: bug
