### ISSUE TITLE
 Statistics in the web panel does not work

### ISSUE THREAD

**Issue by Johnnykson** [donaldzou/WGDashboard#291] opened 2024-08-05 17:50 UTC
Hi! Statistics in the web panel do not work, peers are created, interfaces are turned on and off, but there are no statistics, neither about traffic, nor about the fact that the peer is active.
![Снимок экрана 2024-08-06 004126](https://github.com/user-attachments/assets/3568a6a0-1af0-4c32-b431-73fdaebe1c1a)
At the moment the active peer is trrrrr, but the web panel does not display it, error in the console:
```
Uncaught 
TypeError: Cannot read properties of null (reading 'target')
    at e (content.js:2:88025)
```
![Снимок экрана 2024-08-06 004909](https://github.com/user-attachments/assets/0f9644cf-6fb0-4bdb-b717-93eb078b4fdf)

**Comment by barryboom** [comment] 2024-08-05 18:39
i can confirm i seen this same experience

**Comment by donaldzou** [comment] 2024-08-05 18:42
Ohhhhhhh kay this is something new, I will look into that. Just to confirm, the peers are connected and there are traffic showing on peer side WireGuard?

**Comment by donaldzou** [comment] 2024-08-05 19:22
Nvm... I think is another issue running with Gunicorn, should be perfectly fine in `debug` mode

**Comment by donaldzou** [comment] 2024-08-05 19:48
Some good news, I've managed to fix the issue. It was due to Gunicorn not actually spawn the 2 background threads in main process.. Should be good now :) Thanks again for bringing this up.


<img width="1415" alt="Screenshot 2024-08-05 at 3 43 39 PM" src="https://github.com/user-attachments/assets/1a8cfecc-8324-4c57-8708-525975b52da5">

Regarding @Johnnykson's issue
```
Uncaught 
TypeError: Cannot read properties of null (reading 'target')
    at e (content.js:2:88025)
```
I'm thinking this might cause by your browser or one of the browser plugin? WGDashboard doesn't use any `.js` file named `content.js`

**Comment by Johnnykson** [comment] 2024-08-06 14:02
```
root@v2553761:/opt/wgdashboard/src# ./wgd.sh start
------------------------------------------------------------
[WGDashboard] Starting WGDashboard with Gunicorn in the background.
[WGDashboard] Activate Python Virtual Environment under ./venv
Failed to read config file: ./gunicorn.conf.py
Traceback (most recent call last):
  File "/opt/wgdashboard/src/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 111, in get_config_from_filename
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/wgdashboard/src/./gunicorn.conf.py", line 1, in <module>
    import dashboard
  File "/opt/wgdashboard/src/dashboard.py", line 353, in <module>
    class PeerShareLinks:
  File "/opt/wgdashboard/src/dashboard.py", line 382, in PeerShareLinks
    def addLink(self, Configuration: str, Peer: str, ExpireDate: datetime = None) -> tuple[bool, message]:
NameError: name 'message' is not defined
```
Hi, i see this on the latest version

**Comment by donaldzou** [comment] 2024-08-06 14:19
Hi yes my bad, I forgot to push the latest when I was doing some testing. Should be good now.

**Comment by Johnnykson** [comment] 2024-08-06 14:29
> Hi yes my bad, I forgot to push the latest when I was doing some testing. Should be good now.

I also noticed that the folder is called `wgdashboard` and not `WGDashboard `.
everything is running now, but I can't get into the web panel, it says: 

> Sorry, your username or password is incorrect.

wtf 🤣

**Comment by Johnnykson** [comment] 2024-08-06 14:34
> > Hi yes my bad, I forgot to push the latest when I was doing some testing. Should be good now.
> 
> I also noticed that the folder is called `wgdashboard` and not `WGDashboard `. everything is running now, but I can't get into the web panel, it says:
> 
> > Sorry, your username or password is incorrect.
> 
> wtf 🤣

oh, sorry, I'm an idiot, I should have entered: admin / admin

**Comment by donaldzou** [comment] 2024-08-06 14:37
lol you have a heart attack, just got off to grab breakfast and saw your comment. Let me know if it is working for you and I can close this issue 😁

**Comment by Johnnykson** [comment] 2024-08-06 14:44
> lol you have a heart attack, just got off to grab breakfast and saw your comment. Let me know if it is working for you and I can close this issue 😁

ehhhhh, so far everything is good and works great! Bon appetit!

**Closed** 2024-08-06 14:45 UTC
Labels: bug, v4.0
