### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by p1grishin** [donaldzou/WGDashboard#177] opened 2022-05-04 09:09 UTC
Hello. In order for the connection via 443 and SSL to work, I need to adjust the settings gunicorn.conf.py ?

**Comment by pgalonza** [comment] 2022-06-04 20:15
@p1grishin Hi, for using SSL you need for example using certbot for create TLS certificate and starting gunicorn with SSL parameters
Example - https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wgd.sh#L107

**Comment by p1grishin** [comment] 2023-03-27 21:07
> @p1grishin Hi, for using SSL you need for example using certbot for create TLS certificate and starting gunicorn with SSL parameters Example - https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wgd.sh#L107

Hi, I replaced my gunicorn_start() function with the one listed in your link. After I was given several errors in the log, I realized that there was not enough file wsgi.py I created it https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wsgi.py
The site began to open, but without SSL and redirects from my site to mine.
What could be the problem? You don't need to specify port 443 anywhere, or will guinocorn do it itself?
And yes, I installed certbot

**Comment by p1grishin** [comment] 2023-05-11 21:10
> > > @p1grishin Hi, for using SSL you need for example using certbot for create TLS certificate and starting gunicorn with SSL parameters Example - https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wgd.sh#L107
> > 
> > 
> > Hi, I replaced my gunicorn_start() function with the one listed in your link. After I was given several errors in the log, I realized that there was not enough file wsgi.py I created it https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wsgi.py The site began to open, but without SSL and redirects from my site to mine. What could be the problem? You don't need to specify port 443 anywhere, or will guinocorn do it itself? And yes, I installed certbot
> 
> Did you set value for $SSL env variable? (if you use wgd.sh )

No, I didn't set it. Yes, I use wgd.sh Where can I set it?
Do I need to edit any other files? For example, certbot.ini
And I install the certbot like this https://certbot.eff.org/instructions?ws=webproduct&os=ubuntufocal ?

**Comment by pgalonza** [comment] 2023-05-17 19:42
> > > > @p1grishin Hi, for using SSL you need for example using certbot for create TLS certificate and starting gunicorn with SSL parameters Example - https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wgd.sh#L107
> > > 
> > > 
> > > Hi, I replaced my gunicorn_start() function with the one listed in your link. After I was given several errors in the log, I realized that there was not enough file wsgi.py I created it https://github.com/pgalonza/WGDashboard/blob/ca41cfd8fafd0e0700b4bf6997a8c5388a958d30/src/wsgi.py The site began to open, but without SSL and redirects from my site to mine. What could be the problem? You don't need to specify port 443 anywhere, or will guinocorn do it itself? And yes, I installed certbot
> > 
> > 
> > Did you set value for $SSL env variable? (if you use wgd.sh )
> 
> No, I didn't set it. Yes, I use wgd.sh Where can I set it? Do I need to edit any other files? For example, certbot.ini And I install the certbot like this https://certbot.eff.org/instructions?ws=webproduct&os=ubuntufocal ?

You can execute - export SSL=true

**Comment by DaanSelen** [comment] 2024-10-24 20:39
Duplicate of: https://github.com/donaldzou/WGDashboard/issues/145

If not respond.

**Closed by DaanSelen** 2024-10-24 20:39 UTC
Labels: enhancement
